version: "3.8"
services:
  app:
    container_name: lazy_dev_weather_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./lazy_dev_weather:/home/lazy_dev_weather
      - /lazy_dev_weather/vendor
